server:
  port: ${PORT}
  tomcat:
    max-swallow-size: -1


logging:
  level:
    org:
      springframework:
        web : DEBUG

spring:
  datasource:
    url:  jdbc:postgresql:${DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jooq:
    sql-dialect:  org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

